
- name: Disable ipv6 to fix annoying network changed error
  lineinfile:
    path: "/etc/defualt/grub"
    regexp: "GRUB_CMDLINE_LINUX"
    line:  'GRUB_CMDLINE_LINUX="ipv6.disable=1"'
    state: present
  notify:
    - Update Grub2 config file ubuntu


