
- name: Download the awscli bundle.
  get_url: 
    url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: /tmp/awscliv2.zip
  register: aws_cli_download

- name: Unarchive the installer.
  unarchive: 
    src: /tmp/awscliv2.zip
    dest: /tmp 
    copy: no 
    creates: /tmp/aws
  when: aws_cli_download.changed
  register: aws_cli_unarchive_installer

- name: Install awscli package.
  shell: ./aws/install
  args:
    creates: /usr/bin/aws
  when: aws_cli_unarchive_installer.changed

# - name: Configure AWS.
#   shell: aws configure set {{ item.key }} {{ item.value }} --profile {{ aws_profile }}
#   no_log: True
#   with_dict:
#     aws_access_key_id: "{{ aws_access_key }}"
#     aws_secret_access_key: "{{ aws_secret_key }}"
#     region: "{{ aws_region }}"
#     format: "{{ aws_format }}"
#   become_user: "{{ aws_system_user }}"
#   changed_when: false