
- name: Add an Apt signing key, uses whichever key is at the URL
  ansible.builtin.apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present   
    
- name: Add specified repository into sources list using specified filename
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://apt.releases.hashicorp.com jammy main
    state: present
    filename: hashicorp
- name: Add apt packages
  apt:
    pkg:
      - ansible
      - docker-compose
      - gnupg 
      - software-properties-common
      - curl
      - zsh
      - git
      - python3
      - python3-pip
      - git-lfs
      - conky-all
      - tmux
      - packer
      - terraform
      - vagrant
      - virtualbox
      - virtualbox-guest-additions-iso
      - virtualbox-dkms
      - openssh-server
      - linux-headers-generic
    state: present
    update_cache: yes
  notify: 
    - reconfigure virtualbox-dkms
        

