---

- name: Install Core packages
  include_tasks: "install-core_pkgs.yml"

- name: Install Snap packages
  include_tasks: "install-snap_pkgs.yml"

- name: Install aws cli
  include_tasks: "install-aws.yml"

- name: Config docker for user
  include_tasks: "config-docker.yml"

- name: Init git LFS
  include_tasks: "config-git_lfs.yml"

- name: Enable ssh
  include_tasks: "config-ssh.yml"

- name: Configure zsh terminal
  include_tasks: "config-zsh.yml"

- name: Disable ipv6 via grub
  include_tasks: "disable-ipv6.yml"

- name: Reboot machine to finsih
  reboot: