---
# tasks file for conky
- name: Add apt packages
  apt:
    pkg:
      - conky-all
    state: present
    update_cache: true

- name: Copy conky config across
  copy: 
    src: conkyrc
    dest: ~/.conkyrc
  become_user: "{{ item }}"
  with_items: "{{ conky_users }}"

- name: Copy conky auto start 
  blockinfile:
    path: /usr/share/gnome/autostart/conky.desktop
    block: |
      [Desktop Entry]
      Type=Application
      Name=Conky
      Comment=Start conky script
      Exec=conky -d
      OnlyShowIn=GNOME;
      X-GNOME-Autostart-Phase=Application
    create: yes