---
# tasks file for zsh

- name: Check for OMZ install
  stat:
    path: ~/.oh-my-zsh
  register: omz_present

- name: Download OMZ install script
  get_url:
    url: 'https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh'
    dest: ~/omz-install.sh
    mode: 0755
  when: not omz_present.stat.exists

- name: Run OMZ install script
  command: ~/omz-install.sh --unattended
  register: omz_output
  when: not omz_present.stat.exists

- name: Create fonts directory
  become: true
  file:
    path: /usr/share/fonts/TTF
    mode: '0755'
    state: directory

- name: Copy powerlevel10k recommanded fonts
  copy:
    src: "fonts/{{ item }}"
    dest: "/usr/share/fonts/TTF/{{ item }}"
    mode: '0644'
  become: true
  loop:
    - MesloLGS NF Bold Italic.ttf
    - MesloLGS NF Bold.ttf
    - MesloLGS NF Italic.ttf
    - MesloLGS NF Regular.ttf

- name: Install powerlevel10k.
  git:
    repo: "{{ p10k_repository_url }}"
    dest: "~/.oh-my-zsh/custom/themes/powerlevel10k"
    depth: '1'
    update: no
    version: 'master'
  become_user: "{{ item }}"
  with_items: "{{ p10k_users }}"

- name: Add powerlevel10k to zsh plugin
  lineinfile:
    path: "~/.zshrc"
    regexp: "^ZSH_THEME="
    line: 'ZSH_THEME="powerlevel10k/powerlevel10k"'
    mode: '0644'
    create: yes
  become_user: "{{ item }}"
  with_items: "{{ p10k_users }}"

- name: Enable powerlevel10 instant prompt
  blockinfile:
    path: "~/.zshrc"
    block: |
      if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
        source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
      fi
    insertbefore: BOF
    marker_begin: "BEGIN P10K INSTANT PROMPT"
    marker_end: "END P10K INSTANT PROMPT"

- name: Enable powerlevel10k config file
  blockinfile:
    path: "~/.zshrc"
    block: |
      [[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
    insertafter: EOF
    marker_begin: "BEGIN P10K CONFIG FILE"
    marker_end: "END P10K CONFIG FILE"

- name: Set zsh as default shell
  user:
    name: "{{ item }}"
    shell: "{{ zsh_bin_path }}"
  with_items: "{{ p10k_users }}"
  become: true

- name: Setup powerlevel10k
  copy:
    src: "p10k.zsh"
    dest: '~/.p10k.zsh'
    mode: '0644'
  become_user: "{{ item }}"
  with_items: "{{ p10k_users }}"

- name: Copy dconf file across
  copy:
    src: dconf_zsh_profile.txt
    dest: ~/zsh_profile.txt

- name: Restore profile
  command: 
    cmd: sh -c "dconf load -f /org/gnome/terminal/ < zsh_profile.txt"
  #become: true

- name: Install autosuggestions
  git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions"
    dest: "~/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
    update: yes
    version: 'master'
  become_user: "{{ item }}"
  with_items: "{{ p10k_users }}"

- name: Install syntax highlighting
  git:
    repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    dest: "~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
    update: yes
    version: 'master'
  become_user: "{{ item }}"
  with_items: "{{ p10k_users }}"

- name: Add powerlevel10k to zsh plugin
  lineinfile:
    path: "~/.zshrc"
    regexp: "^plugins="
    line: 'plugins=(git web-search history-substring-search zsh-autosuggestions colored-man-pages zsh-syntax-highlighting)'
    mode: '0644'
    create: yes
  become_user: "{{ item }}"
  with_items: "{{ p10k_users }}"

- name: tidy up
  file: 
    path: "{{ item }}"
    state: ansent
  with_items: 
    - ~/zsh_profile.txt
    - ~/omz-install.sh