---
# tasks file for docker

- name: Add apt packages
  apt:
    pkg:
      - docker-compose
      - software-properties-common
    state: present
    update_cache: yes

- name: Install snaps
  community.general.snap:
    name:
      - docker

- name: Ensure group docker exists
  ansible.builtin.group:
    name: docker
    system: true
    state: present

- name: Add user to docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  with_items: "{{ docker_users }}"
  
- name: disable docker snap
  community.general.snap:
    name: docker
    state: disabled
    
- name: enable docker snap
  community.general.snap:
    name: docker
    state: enabled
         